name: Docker

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: adamkingdotnet/.github/.github/workflows/ghcr-publish.yml@ed14dbf099aa00cee37af1bb7f8cd6d4deb78a36 # main
    secrets: inherit
