name: Docker

on:
  push:
    branches: [main]

permissions:
  contents: read
  packages: write

jobs:
  publish:
    uses: adamkingdotnet/.github/.github/workflows/ghcr-publish.yml@main
    secrets: inherit
